name:                haskell-do
version:             0.0.0
synopsis:            The Haskell code editor focused on interactive development
description:         Please see README.md
homepage:            https://github.com/theam/haskell-do#readme
license:             Apache-2.0
author:              Theam
maintainer:          nick@theam.io
copyright:           2017 Theam
category:            Editor
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

when:
  - condition: impl(ghcjs)
    dependencies:
      - ghcjs-base

executables:
  haskell-do:
    source-dirs:      common
    main:             Main.hs

    when:
      - condition: impl(ghcjs)
        then:
          source-dirs: gui
        else:
          source-dirs:
            - core
            - orchestrator

